name: build-stage-three
on:
  push:
    paths:
      - '*'
      - '.github/workflows/**'
      - 'stage_3_**'
jobs:
  build-stage-three:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build-stage-three
        timeout-minutes: 5
      - run: npm run is-repo-clean
